export const data=[

    {region:"ARIANA" ,poste:"TUNIS CARTHAGE",code:2035 },
    {region:"ARIANA" ,poste:"CITE ENNASR ARIANA",code:2001 },
    {region:"ARIANA" ,poste:"BORJ BACCOUCH",code:2027 },
    {region:"ARIANA" ,poste:"SOKRA",code:2036 },
    {region:"ARIANA" ,poste:"ARIANA",code:2080 },
    {region:"ARIANA" ,poste:"ARIANA GEANT",code:2002 },
    {region:"ARIANA" ,poste:"MENZAH 6",code:2091},
    {region:"ARIANA" ,poste:"CITE LA GAZELLE",code:2083 },
    {region:"BEJA" ,poste:"MJEZ ELBEB",code:9070 },
    {region:"BEJA" ,poste:"TBORSOK",code:9040 },
    {region:"BEJA" ,poste:"BEJA",code:9000 },
    {region:"BEJA" ,poste:"DOUGGA",code:9032 },
    {region:"BEN AROUS" ,poste:"RADES MEDINA",code:2098 },
    {region:"BEN AROUS" ,poste:"MHAMDIA",code:1145 },
    {region:"BEN AROUS" ,poste:"HAMMEM LINF",code:2045 },
    {region:"BEN AROUS" ,poste:"RADES",code:2040 },
    {region:"BEN AROUS" ,poste:"EZZAHRA",code:2034 },
    {region:"BEN AROUS" ,poste:"BEN AROUS",code:2013 },
    {region:"BEN AROUS" ,poste:"ERISALA",code:2044 },
    {region:"BEN AROUS" ,poste:"EZZAHRA EL HABIB",code:2065 },
    {region:"BEN AROUS" ,poste:"NOUVELLE MEDINA ",code:2063 },
    {region:"BEN AROUS" ,poste:"MOUROUJ 1",code:2074 },
    {region:"BEN AROUS" ,poste:"MOUROUJ 3",code:2068 },
    {region:"BEN AROUS" ,poste:"MEGRINE RIADH",code:2014 },
    {region:"BEN AROUS" ,poste:"MORNEG",code:2090 },
    {region:"BEN AROUS" ,poste:"MEGRINE",code:2033 },
    {region:"BEN AROUS" ,poste:"MOUROUJ 1",code:2074 },
    {region:"BIZERTE" ,poste:"BIZERTE",code:7000 },
    {region:"BIZERTE" ,poste:"RAS DJEBEL",code:7070 },
    {region:"BIZERTE" ,poste:"BIZERTE BEB MATER",code:7061 },
    {region:"BIZERTE" ,poste:"MENZEL BOURGUIBA",code:7050 },
    {region:"BIZERTE" ,poste:"MZL BOURGUIBA ENNAQJEH ",code:7072 },
    {region:"BIZERTE" ,poste:"MENZEL  JEMIL ",code:7080 },
    {region:"GABES" ,poste:"GABES  HACHED",code:6001 },
    {region:"GABES" ,poste:"GABES B BHAR ",code:6000 },
    {region:"GABES" ,poste:"CITE EL AMEL",code:6033 },
    {region:"GABES" ,poste:"EL HAMMA",code:6020 },
    {region:"GABES" ,poste:"MARETH   ",code:6080 },
    {region:"GABES" ,poste:"GAFSA   ",code:2100 },
    {region:"GABES" ,poste:"GAFSA CITE ENNOUR   ",code:2123 },
    {region:"GABES" ,poste:"GAFSA EL INTILAKA   ",code:2117 },
    {region:"GABES" ,poste:"METLAOUI ",code:2130 },
    {region:"GABES" ,poste:"ELGATTAR",code:2180 },
    {region:"GABES" ,poste:"ERDAYEF",code:2120 },
    {region:"GABES" ,poste:"GAFSA GAR",code:2111 },
    {region:"JENDOUBA" ,poste:"AIN DRAHEM ",code:8130 },
    {region:"JENDOUBA" ,poste:"BOUSSALEM ",code:8170 },
    {region:"JENDOUBA" ,poste:"TABARKA ",code:8110 },
    {region:"JENDOUBA" ,poste:"JENDOUBA ",code:8100 },
    {region:"JENDOUBA" ,poste:"GHARDIMAO ",code:8160 },
    {region:"KAIRAOUAN" ,poste:"BOUHAJLA ",code:3180 },
    {region:"KAIRAOUAN" ,poste:"KAIRAOUAN OKBA ",code:3140 },
    {region:"KAIRAOUAN" ,poste:"KAIRAOUAN SUD ",code:3131 },
    {region:"KAIRAOUAN" ,poste:"KAIRAOUAN  ",code:3100 },
    {region:"KAIRAOUAN" ,poste:"OUSLETIA  ",code:3120 },
    {region:"KAIRAOUAN" ,poste:"HAJEB LAAYOUN  ",code:3160 },
    {region:"KAIRAOUAN" ,poste:"CITE HAJJEM  ",code:3129 },
    {region:"KAIRAOUAN" ,poste:"CHRERDA  ",code:3116 },
    {region:"KAIRAOUAN" ,poste:"CITE ENNASR KAIRAOUAN",code:3182 },
    {region:"KAIRAOUAN" ,poste:"CITE IBN JAZZAR",code:3199 },
    {region:"KAIRAOUAN" ,poste:"HAFFOUZ",code:3130 },
    {region:"KASSERINE" ,poste:"SBIBA",code:1270 },
    {region:"KASSERINE" ,poste:"FERYENA",code:1240 },
    {region:"KASSERINE" ,poste:"TELA",code:1210 },
    {region:"KASSERINE" ,poste:"KASSERINE",code:1200 },
    {region:"KASSERINE" ,poste:"SBEITLA",code:1250 },
    {region:"KEBILI" ,poste:"DOUZ",code:4260 },
    {region:"KEBILI" ,poste:"KEBILI",code:4200 },
    {region:"KEBILI" ,poste:"KEBILI BIEZ",code:4280 },

    {region:"KEBILI" ,poste:"SOUK LAHAD",code:4230 },

    {region:"KEF" ,poste:"DAHMENI",code:7170 },
    {region:"KEF" ,poste:"KEF",code:7100 },
    {region:"KEF" ,poste:"TEJROUIN",code:7150 },
    {region:"KEF" ,poste:"KEF OUEST",code:7117 },
    {region:"MAHDIA" ,poste:"HEKAIMA",code:5131 },
    {region:"MAHDIA" ,poste:"MAHDIA REPUBLIC",code:5150 },
    {region:"MAHDIA" ,poste:"CHEBBA",code:5170 },
    {region:"MAHDIA" ,poste:"MAHDIA",code:5100 },
    {region:"MAHDIA" ,poste:"MAHDIA HIBOUN",code:5111 },
    {region:"MAHDIA" ,poste:"KSSOUR ESSEF",code:5180 },
    {region:"MAHDIA" ,poste:"SOUASSI",code:5140 },
    {region:"MAHDIA" ,poste:"EL JAM",code:5150 },
    {region:"MANNOUBA" ,poste:"TEBOURBA",code:1130 },
    {region:"MANNOUBA" ,poste:"MORNAGUIA",code:1110 },
    {region:"MANNOUBA" ,poste:"DENDEN",code:2011 },
    {region:"MANNOUBA" ,poste:"MANNOUBA",code:2010 },
    
    {region:"MEDNIN" ,poste:"EL MAY",code:4175 },
    
    {region:"MEDNINE" ,poste:"AJIM",code:4135 },
    {region:"MEDNINE" ,poste:"MOUENSA",code:4144 },
    {region:"MEDNINE" ,poste:"MIDDOUN",code:4116 },
    {region:"MEDNINE" ,poste:"ZARZIS",code:4170 },
    {region:"MEDNINE" ,poste:"MEDNINE",code:4100 },
    {region:"MEDNINE" ,poste:"JERBA",code:4180 },
    {region:"MEDNINE" ,poste:"JERBA AEROPORT",code:4120 },
    
    {region:"MEDNINE" ,poste:"CEDOUIKECH",code:4145 },
    {region:"MEDNINE" ,poste:"AKROU",code:4176 },
    {region:"MEDNINE" ,poste:"BENGERDEN",code:4160 },
    {region:"MEDNINE" ,poste:"SOUIHEL",code:4173 },
    {region:"MONASTIR" ,poste:"KSAR HELEL",code:5070 },
    {region:"MONASTIR" ,poste:"MOKNINE",code:5050 },
    {region:"MONASTIR" ,poste:"JAMMEL",code:5020 },
    {region:"MONASTIR" ,poste:"MONASTIR",code:5000 },
    {region:"MONASTIR" ,poste:"MONASTIR REPUBLIC ",code:5060 },
    {region:"MONASTIR" ,poste:"TEBOLBA ",code:5080 },
    {region:"NABEUL" ,poste:"KELIBIA ",code:8090 },
    {region:"NABEUL" ,poste:"YESSMINE EL HAMMAMET ",code:8057 },
    {region:"NABEUL" ,poste:"NABEUL THAMEUR ",code:8062 },
    {region:"NABEUL" ,poste:"BENI KHIAR ",code:8060 },
    {region:"NABEUL" ,poste:"KORBA ",code:8070 },
    {region:"NABEUL" ,poste:"SOLIMAN ",code:8020 },
    {region:"NABEUL" ,poste:"MREZGA ",code:8058 },
    {region:"NABEUL" ,poste:"GROMBALIA ",code:8030 },
    {region:"NABEUL" ,poste:"DAAR CHABEN FEHRI ",code:8011 },
    {region:"NABEUL" ,poste:"HAMMAMET ",code:8050 },
    {region:"NABEUL" ,poste:"NABEUL ",code:8000 },
    {region:"SFAX" ,poste:"MERKEZ CHIHYA ",code:3041 },
    {region:"SFAX" ,poste:"MERKEZ BOUASIDA ",code:3031 },
    {region:"SFAX" ,poste:"CITE EL HABIB ",code:3052 },
    {region:"SFAX" ,poste:"SIDI ABBES ",code:3062 },
    {region:"SFAX" ,poste:"SFAX JADIDA ",code:3027 },
    {region:"SFAX" ,poste:"MERKEZ EL ALIA ",code:3051 },
    {region:"SFAX" ,poste:"SFAX 15 NOVEMBRE ",code:3089 },
    {region:"SFAX" ,poste:"CITE KHAYRI ",code:3079 },
    {region:"SFAX" ,poste:"CITE BAHRI ",code:3064 },
    {region:"SFAX" ,poste:"ESSKHIRA ",code:3050 },
    {region:"SFAX" ,poste:"SFAX",code:3000 },
    {region:"SFAX" ,poste:"KARKENA ",code:3070 },
    {region:"SFAX" ,poste:"SFAX HACHED ",code:3069 },
    {region:"SFAX" ,poste:"EL BOSTENE ",code:3099 },
    {region:"SFAX" ,poste:"TYNA ",code:3083 },
    {region:"SFAX" ,poste:"EL AGUEREB ",code:3030 },
    {region:"SFAX" ,poste:"SAKIYET EZZIT ",code:3021  },
    {region:"SFAX" ,poste:"JBENNIYENA ",code:3080 },
    {region:"SFAX" ,poste:"EL HENCHA",code:3010 },
    {region:"SFAX" ,poste:"SFAX MAGHREB ARABE ",code:3049 },
    {region:"SFAX" ,poste:"EL MAHRES ",code:3060 },
    {region:"SFAX" ,poste:"SAKKIET EDDAIER",code:3011 },
    {region:"SIDI BOUZID" ,poste:"BENNAOUN ",code:9120 },
    {region:"SIDI BOUZID" ,poste:"BIR EL HFAY ",code:9113 },
    {region:"SIDI BOUZID" ,poste:"JELMA ",code:9110 },
    {region:"SIDI BOUZID" ,poste:"MOKKNESI ",code:9140 },
    {region:"SIDI BOUZID" ,poste:"ERGGUEB ",code:9170 },
    {region:"SIDI BOUZID" ,poste:"SIDI BOUZID ",code:9100 },
    
    
    
    
    
    
    
    
]


export const detailscaracteristique=[
    {constructeur:'Alpina',model:['B3','B5','B6','B7','B10','B12','D3','D10','Roadster S','AUTRE']},
    {constructeur:'Alpha Romeo',model:['8C','33','75','90','145','146','149','147','155','159','156','AlphaSud','164','166','Alfetta','Brera','Guilia','CrossWagon','GT','Mi.To','GTV','RZ/SZ','Spider','SportWagon','Sprint','Autre'] },
    {constructeur:'Audi' ,model:['80','90','200','A1','100','A2','A3','A4','A5','A6','A8','AllRoad','Cabrio','Coupe','Q5','Q7','Quatro','R8','RS2','RS4','R2','RS8','S2','S3','S4','S5','S6','S8','TT','Autre','V8','Q8','E-Tron'] },
    {constructeur:'BMW',model:['M1','M3','M4','M6','X1','X2','X3','X5','X6','Z3','Z1','Z3M','Z4M','Z4','Z8','Serie1','Serie2','Serie3','Serie5','Serie6','Serie7','Serie8','Autre']},
    {constructeur:'Dacia',model:['Logan','Sandero','Pick-up','Autre', 'Duster']},
    {constructeur:'Chevrolet',model:['2500','Astro Van','Alero','Avalanche','Aveo','Beretta','Blazer','c1500','Camarro','Captivia','Caprice','Cavalier','Chevy Van','El Camino','Corsica','Cruze','Epica','G','HHR','Evanda','Impala','K1500','K30','Kalos','Lacetti','Lumina','Matiz','Malibu','Rezzo','Nubbira','S10','SilverDao','Spark','Suburban','Tahoe','SSR','Trans sport','Venture','Autre']},
    {constructeur:'Citroen',model:['15','11','Acadine','2CV','AMI','AX','B14','AXEL','BX','Berlingo','C1','C-CROSSER','C2','C3','C15','C25','C3-PICASSO','C3-Pluriel','C4-PICASSO','C4','C5','C6','C8','CX','DS','DS3','DS4','DS5','Dyane','Grand-C4-Piccasso','JUMPY','GSA','JUMPER','LNA','Mehari','Nemo','Saxo','SM','Torpedo','Visa','XM','Xantia','Xsara','Xsara-Piccasso','ZX','AUTRE']},
    {constructeur:'DS',model:['DS3','DS4','DS5','DS7','DS9','AUTRE']},
    {constructeur:'FERRARI',model:['208','246','250','275','288','308','328','330','348','360','400','356','412','550','456','512','575','599GTB','612','750','DAYTOUNA','DINO-GT4','ENZO-FERRARI','F40','F50','MONDIAL','F355','SuperAmerica','Tesstarossa','AUTRE']}
]